version: "3.7"
services:
  pointing_poker1:
    image: pointing_poker:latest
    restart: always
    environment:
      SECRET_KEY_BASE: xpxxkkIHCWlEskjNy02KxBXXVMGoOaYvf79c1wfjw9MX1mmDYK/okrN5xsk2Q4ZJ
      HOST: localhost
      PORT: 4001
    ports:
      - 4001:4000

  pointing_poker2:
    image: pointing_poker:latest
    restart: always
    environment:
      SECRET_KEY_BASE: xpxxkkIHCWlEskjNy02KxBXXVMGoOaYvf79c1wfjw9MX1mmDYK/okrN5xsk2Q4ZJ
      HOST: localhost
      PORT: 4002
    ports:
      - 4002:4000
